//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYDX18DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentsLog
    {
        public int ID { get; set; }
        public string OpType { get; set; }
        public Nullable<int> ContentsID { get; set; }
        public string BfContentsUpdate { get; set; }
        public string AfContentsUpdate { get; set; }
        public string BfTitleUpdate { get; set; }
        public string ATitleUpdate { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string AccountUser { get; set; }
    }
}
