//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYDX18DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contents
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string XContents { get; set; }
        public string Mark { get; set; }
        public string QRCodeURL { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string AccountUser { get; set; }
        public Nullable<int> IsDelete { get; set; }
    }
}
